### ISSUE TITLE
Setup can't tell if PC has enough space to continue installing windows 11

### ISSUE THREAD

**Issue by cyrdodi** [coofcookie/Windows11Upgrade#10]
Hi, I have 75 GB free in my drive C, I believe it's more than windows recomendation to updgare windows 11, but when I get this error from Windows 11 Setup that says
"We can't tell if your PC has enough space to continue installing Windows 11. Try restarting Setup."
I've been restarting the setup three times but it always stuck in this error message.

**Comment by BochoySNR** [comment]
I have the same problem.  From what I understand it can be a badly downloaded iso.  Re-download the iso again and click on the verify download box after iso download and follow the instructions to use checksum tool on the Microsoft download page to make sure both checksums match.  I'm going to try it again and will re-post if it works.

https://www.microsoft.com/en-gb/software-download/windows11


Hope this helps

**Comment by BochoySNR** [comment]
Tried, sorry it didn't work.  Will keep on trying to find a fix, if so I will post instructions here

**Comment by cyrdodi** [comment]
Does your PC have dual boot setup?

**Comment by BochoySNR** [comment]
Hi

Tried a number of methods and failed but this worked for me very well. It only works for a clean install of Windows 11 but this YouTuber has another video for an upgrade method.

https://youtu.be/57yI6TMgIFI

Hope it helps.

**Comment by cyrdodi** [comment]
Okay I will try this method, thank you very much.

**Comment by BochoySNR** [comment]
Great, pls post and let us know how it goes

**Comment by cyrdodi** [comment]
![image](https://user-images.githubusercontent.com/4262515/139630197-2f54915f-b0a0-4749-af78-a8e8f03b5e4c.png)
Still no luck 😞

**Comment by BochoySNR** [comment]
Hi

Sorry it didn't work. I got the same error message every time until I tried this method. Did you follow his instructions to the letter and create a bootable USB drive?

**Comment by cyrdodi** [comment]
I did, but the instruction is to create an ISO file not bootable USB drive, or am I missing something?

**Comment by BochoySNR** [comment]
Hi

Apologies, link was for other method.  Here's the method I used that worked:

https://www.youtube.com/watch?v=nwF9k9M-UE8&list=WL&index=3

I also found this on github if above link doesn't work

https://github.com/coofcookie/Windows11Upgrade

Please let me know how you get on.  All the best

**Comment by BochoySNR** [comment]
Just realized I didn't answer you earlier question. No my PC does not have dual boot setup 🙂

**Comment by zQueal** [comment]
Use this utility to download the Windows 11 ISO, and then use [Rufus](https://github.com/pbatard/rufus) to create a bootable USB.

**Comment by cyrdodi** [comment]
Sorry for the late reply, I can't afford a clean install right now, but maybe later when I have time I'll try it.
Thank you for the help guys.

**Comment by cyrdodi** [comment]
After I uninstall my ubuntu dan delete the partition, now I'm succesfully upgrade to windows 11, no need to clean install.
