### ISSUE TITLE
Does this tool bypass Microsoft from blocking updates on unsupported Windows 11 devices ?

### ISSUE THREAD

**Issue by FurryOfficial** [coofcookie/Windows11Upgrade#21]
As the title said:
**Does this tool bypass Microsoft from blocking updates on unsupported Windows 11 devices ?**

**Comment by coofcookie** [comment]
Hi, 

Windows 11 is currently not blocking updates on unsupported devices, so there is nothing to bypass.

coofcookie

**Comment by Pedro1234-code** [comment]
I think yes because it delete C:\$Windows_bt\appreiseres.dll or C:\Windows\System32\vsldr.exe, so Microsoft can't detect if your hardware is compatible or no.
