### ISSUE TITLE
I cant upgrade to windows 11 with all my files and apps since its saying i chose to download windows 11 in a different langue than im using on windows 11

### ISSUE THREAD

**Issue by MonkeCommitsKill** [coofcookie/Windows11Upgrade#28]
![kuva_2022-03-20_185753](https://user-images.githubusercontent.com/97696740/159173619-7b4bff73-514e-4c36-b1a6-452112ccff72.png)

so i downloaded it in english and my windows 10 is in english so is there any fix?

**Comment by Dark-Yox** [comment]
You tired downloading the ISO using the software ?

**Comment by win98se** [comment]
There are two variants of English, United States (en-US) and United Kingdom (en-GB). You may have downloaded the incorrect one.

**Comment by MonkeCommitsKill** [comment]
i got it working25.3.2022 15.50 Othmane El Alami ***@***.***> kirjoitti:
You tired downloading the ISO using the software ?
