### ISSUE TITLE
does this actually works

### ISSUE THREAD

**Issue by agentanger** [coofcookie/Windows11Upgrade#29]
so i got windows 10, i dont got the windows 11 iso file but i clicked to install it from the windows11upgrade, im not sure if this is safe so if i press upgrade then a blue screen will pop up and say windows 11 is installing and it will be a button saying cancel? or how does this work. and ram is a problem too? like i got 3 gb ram will i get a error

**Comment by Pedro1234-code** [comment]
no, its fine to upgrade with a windows 10 iso
