### ISSUE TITLE
BROOO IT WORKEDD

### ISSUE THREAD

**Issue by agentanger** [coofcookie/Windows11Upgrade#30]
BRO IT ACTUALLY WORK EVEN IF YOU HAVE 3 GB RAM OF ANYTHING AND U CAN GET UPDATES TOO BRO IM SO HAPYY IM POSTING THIS ON WINDOWS 11 
![Screenshot 2022-05-01 154948](https://user-images.githubusercontent.com/104687776/166159718-e7734ba8-6b83-494c-aa79-0e24b8a714bd.png)

**Comment by coofcookie** [comment]
Glad you're happy :)
