### ISSUE TITLE
[simplification suggestion] import a reg file, instead of complex powershell actions 

### ISSUE THREAD

**Issue by eladkarako** [coofcookie/Windows11Upgrade#34]
just import a [reg files](https://gist.github.com/eladkarako/c593b72d8df7b3d195b10204252bafb3) to the registry of the machine you're working on instead most of this: https://github.com/coofcookie/Windows11Upgrade/blob/dd177581de033d45a98f41afe4c77b168058fc6e/Windows11Upgrade/win11_installSystem.cs

**Comment by Aritz331** [comment]
@eladkarako how do you import a reg file through command line?

**Comment by eladkarako** [comment]
the command line is `reg import filename.reg`  

the filename is something [like this](https://github.com/rushiranpise/win11devbypass/blob/main/bypass.reg):

```reg  
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WindowsSelfHost\Applicability]
"BranchName"="Dev"
"Ring"="External"
"ContentType"="Mainline"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WindowsSelfHost\UI\Selection]
"UIContentType"="Mainline"
"UIBranch"="Dev"
"UIRing"="External"

[HKEY_LOCAL_MACHINE\SYSTEM\Setup\LabConfig]
"BypassCPUCheck"=dword:00000001
"BypassStorageCheck"=dword:00000001
"BypassRAMCheck"=dword:00000001
"BypassTPMCheck"=dword:00000001
"BypassSecureBootCheck"=dword:00000001

[HKEY_LOCAL_MACHINE\SYSTEM\Setup\MoSetup]
"AllowUpgradesWithUnsupportedTPMOrCPU"=dword:00000001
"BypassCPUCheck"=dword:00000001
"BypassStorageCheck"=dword:00000001
"BypassRAMCheck"=dword:00000001
"BypassTPMCheck"=dword:00000001
"BypassSecureBootCheck"=dword:00000001
```

you can try it and check it was entered by opening regedit (or better yet registry-workshop) and navigating to the key.  
I thing running `reg` as a normal admin should be fine.

**Comment by eladkarako** [comment]
if you are using dism to mount `install.wim`,  
you should mount the registry files into your registry hive,  
I've tried it and didn't make it work though..  

https://gist.github.com/eladkarako/b4ae3ee64e42e1a7fb3082160098ebaf#note-the-following-created-a-corrupted-installation-that-kept-restartingi-guess-something-went-wrong-with-mountingunmountingreg-loadunloadesd-compressionyou-can-follow-those-below-but-youll-probably-wont-be-able-to-enjoy-a-workable-windows
