### ISSUE TITLE
App not opening

### ISSUE THREAD

**Issue by axellslade** [coofcookie/Windows11Upgrade#9]
Hi!
When I double click the app, nothing happens(doesn't launch). 
I tried disabling my AV(Avast), rebooting my PC, making sure the iso isn't mounted.
It's set to run as admin by default, so that's not an issue.
Any help?

**Comment by korboisgay** [comment]
you have too run it as administrator

**Comment by axellslade** [comment]
My account is an admin one, and I did try running it as admin. It works fine in safe mode, so it's something with Avast and/or Adguard that I use but I didn't have time to troubleshoot them.
